USE [TraderDB];
GO

SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

/*
    Preserve leadership-source missingness and activate its strategy identity under ADR-0043.

    Expected preconditions:
      - dbo.LeadershipData, dbo.StrategyVersion, dbo.StrategyVersionModel, and the
        calibration evidence-ledger tables exist.
      - The complete strategy code-identity columns exist. First application has the
        exact enabled/trusted legacy ADR-0042 check; rerun has the exact enabled/trusted
        strengthened check installed by this migration.
      - On first application, all three Active* columns are INT NOT NULL, the new
        leadership constraint is absent, and the sole active strategy is the exact
        v3.1-rs-date-aligned predecessor.
      - On an idempotent rerun, all three Active* columns are INT NULL, the exact
        leadership constraint is enabled and trusted, and the exact v3.2 successor
        is already the sole active strategy.

    Data effects:
      - Makes ActiveAdvancers, ActiveDecliners, and ActiveN nullable as one observation.
      - Converts only the legacy 0/0/0 sentinel triple to NULL/NULL/NULL.
      - Adds a trusted check requiring either complete missingness or one complete,
        non-negative observation whose BIGINT advancer/decliner sum does not exceed N.
      - Replaces the legacy ADR-0042 code-identity check with a trusted strengthened
        form that explicitly requires both identity values before checking their lengths.
      - Clones every threshold and model association from the fixed v3.1 predecessor
        into the fixed v3.2-leadership-missingness identity, then activates v3.2.
      - Does not update, relabel, invalidate, or delete any historical CalibrationRun,
        candidate, lens, outcome-definition, or candidate-outcome row or reference.

    Recovery:
      - Schema, sentinel normalization, strategy cloning, and activation are one
        SERIALIZABLE transaction with XACT_ABORT. Any failed guard rolls back the unit.
      - After a committed result, use the required fresh verified backup or a separately
        authorized corrective migration; do not edit this file after application.

    Review and execute manually only after a fresh verified backup and explicit
    authorization. Do not deploy a DACPAC.
*/

IF OBJECT_ID(N'dbo.LeadershipData', N'U') IS NULL
    OR OBJECT_ID(N'dbo.StrategyVersion', N'U') IS NULL
    OR OBJECT_ID(N'dbo.StrategyVersionModel', N'U') IS NULL
    OR OBJECT_ID(N'dbo.CalibrationRun', N'U') IS NULL
    OR OBJECT_ID(N'dbo.CalibrationCandidate', N'U') IS NULL
    OR OBJECT_ID(N'dbo.CalibrationLensEvaluation', N'U') IS NULL
    OR OBJECT_ID(N'dbo.CalibrationOutcomeDefinition', N'U') IS NULL
    OR OBJECT_ID(N'dbo.CalibrationCandidateOutcome', N'U') IS NULL
    THROW 51070, 'Required leadership, strategy, or calibration evidence tables do not exist.', 1;

DECLARE @PredecessorId UNIQUEIDENTIFIER = '99D52317-8D16-4F2A-8B97-AE9698972F55';
DECLARE @PredecessorName NVARCHAR(32) = N'v3.1-rs-date-aligned';
DECLARE @PredecessorCodeCommit NVARCHAR(128) = N'c51c0849fd1311b3797cc664a19988e553bbe122';
DECLARE @PredecessorDecisionRef NVARCHAR(64) = N'ADR-0041';
DECLARE @SuccessorId UNIQUEIDENTIFIER = '2BD1A7D0-D144-4A7B-9FA4-49606AB7E963';
DECLARE @SuccessorName NVARCHAR(32) = N'v3.2-leadership-missingness';
DECLARE @SuccessorCodeCommit NVARCHAR(128) = N'fad4b968244d57a6224cb7ab137774a9bff4b645';
DECLARE @SuccessorDecisionRef NVARCHAR(64) = N'ADR-0043';
DECLARE @IsFirstApplication BIT;
DECLARE @ActiveColumnCount INT;
DECLARE @NullableActiveColumnCount INT;
DECLARE @LeadershipConstraintDefinition NVARCHAR(MAX);
DECLARE @LeadershipConstraintNormalized NVARCHAR(MAX);
DECLARE @LeadershipConstraintCount INT;
DECLARE @ExpectedLeadershipConstraintDefinition NVARCHAR(MAX);
DECLARE @ExpectedLeadershipConstraintNormalized NVARCHAR(MAX);
DECLARE @ExpectedLeadershipConstraintCount INT;
DECLARE @StrategyIdentityConstraintDefinition NVARCHAR(MAX);
DECLARE @StrategyIdentityConstraintNormalized NVARCHAR(MAX);
DECLARE @StrategyIdentityConstraintCount INT;
DECLARE @ExpectedLegacyStrategyIdentityConstraintDefinition NVARCHAR(MAX);
DECLARE @ExpectedLegacyStrategyIdentityConstraintNormalized NVARCHAR(MAX);
DECLARE @ExpectedLegacyStrategyIdentityConstraintCount INT;
DECLARE @ExpectedFinalStrategyIdentityConstraintDefinition NVARCHAR(MAX);
DECLARE @ExpectedFinalStrategyIdentityConstraintNormalized NVARCHAR(MAX);
DECLARE @ExpectedFinalStrategyIdentityConstraintCount INT;
DECLARE @SentinelRowsBefore BIGINT;
DECLARE @NormalizedSentinelCount BIGINT = 0;
DECLARE @LeadershipRowsBefore BIGINT;
DECLARE @StrategyVersionRowsBefore BIGINT;
DECLARE @StrategyVersionModelRowsBefore BIGINT;
DECLARE @CalibrationRunRowsBefore BIGINT;
DECLARE @CalibrationCandidateRowsBefore BIGINT;
DECLARE @CalibrationLensRowsBefore BIGINT;
DECLARE @CalibrationDefinitionRowsBefore BIGINT;
DECLARE @CalibrationOutcomeRowsBefore BIGINT;
DECLARE @PredecessorModelCount BIGINT;

DECLARE @CalibrationRunReferences TABLE
(
    [RunId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [StrategyVersionId] UNIQUEIDENTIFIER NULL
);

DECLARE @CalibrationCandidateReferences TABLE
(
    [CandidateId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [RunId] UNIQUEIDENTIFIER NOT NULL
);

DECLARE @CalibrationLensReferences TABLE
(
    [LensEvaluationId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [CandidateId] UNIQUEIDENTIFIER NOT NULL
);

DECLARE @CalibrationOutcomeReferences TABLE
(
    [CandidateOutcomeId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [CandidateId] UNIQUEIDENTIFIER NOT NULL,
    [OutcomeDefinitionId] UNIQUEIDENTIFIER NOT NULL
);

BEGIN TRANSACTION;

-- Ask this SQL Server engine to serialize the intended expressions. Comparing
-- its own definitions avoids hand-maintained canonical text while retaining every
-- parenthesis, operator, comma, and operand boundary during later normalization.
CREATE TABLE #ExpectedLegacyStrategyIdentityConstraint
(
    [InitialCodeCommit] NVARCHAR(128) NULL,
    [DecisionRef] NVARCHAR(64) NULL,
    CHECK
    (
        ([InitialCodeCommit] IS NULL AND [DecisionRef] IS NULL)
        OR
        (
            LEN(LTRIM(RTRIM([InitialCodeCommit]))) BETWEEN 7 AND 128
            AND LEN(LTRIM(RTRIM([DecisionRef]))) BETWEEN 1 AND 64
        )
    )
);

CREATE TABLE #ExpectedFinalStrategyIdentityConstraint
(
    [InitialCodeCommit] NVARCHAR(128) NULL,
    [DecisionRef] NVARCHAR(64) NULL,
    CHECK
    (
        ([InitialCodeCommit] IS NULL AND [DecisionRef] IS NULL)
        OR
        (
            [InitialCodeCommit] IS NOT NULL
            AND [DecisionRef] IS NOT NULL
            AND LEN(LTRIM(RTRIM([InitialCodeCommit]))) BETWEEN 7 AND 128
            AND LEN(LTRIM(RTRIM([DecisionRef]))) BETWEEN 1 AND 64
        )
    )
);

CREATE TABLE #ExpectedLeadershipConstraint
(
    [ActiveAdvancers] INT NULL,
    [ActiveDecliners] INT NULL,
    [ActiveN] INT NULL,
    CHECK
    (
        (
            [ActiveAdvancers] IS NULL
            AND [ActiveDecliners] IS NULL
            AND [ActiveN] IS NULL
        )
        OR
        (
            [ActiveAdvancers] IS NOT NULL
            AND [ActiveDecliners] IS NOT NULL
            AND [ActiveN] IS NOT NULL
            AND [ActiveAdvancers] >= 0
            AND [ActiveDecliners] >= 0
            AND [ActiveN] > 0
            AND CONVERT(BIGINT, [ActiveAdvancers]) + [ActiveDecliners] <= [ActiveN]
        )
    )
);

SELECT
    @ExpectedLegacyStrategyIdentityConstraintCount = COUNT(*),
    @ExpectedLegacyStrategyIdentityConstraintDefinition = MAX([definition])
FROM tempdb.sys.check_constraints
WHERE [parent_object_id] = OBJECT_ID(N'tempdb..#ExpectedLegacyStrategyIdentityConstraint');

SELECT
    @ExpectedFinalStrategyIdentityConstraintCount = COUNT(*),
    @ExpectedFinalStrategyIdentityConstraintDefinition = MAX([definition])
FROM tempdb.sys.check_constraints
WHERE [parent_object_id] = OBJECT_ID(N'tempdb..#ExpectedFinalStrategyIdentityConstraint');

SELECT
    @ExpectedLeadershipConstraintCount = COUNT(*),
    @ExpectedLeadershipConstraintDefinition = MAX([definition])
FROM tempdb.sys.check_constraints
WHERE [parent_object_id] = OBJECT_ID(N'tempdb..#ExpectedLeadershipConstraint');

DROP TABLE #ExpectedLegacyStrategyIdentityConstraint;
DROP TABLE #ExpectedFinalStrategyIdentityConstraint;
DROP TABLE #ExpectedLeadershipConstraint;

IF @ExpectedLegacyStrategyIdentityConstraintCount <> 1
    OR @ExpectedLegacyStrategyIdentityConstraintDefinition IS NULL
    OR @ExpectedFinalStrategyIdentityConstraintCount <> 1
    OR @ExpectedFinalStrategyIdentityConstraintDefinition IS NULL
    OR @ExpectedLeadershipConstraintCount <> 1
    OR @ExpectedLeadershipConstraintDefinition IS NULL
    THROW 51097, 'The engine did not serialize exactly one intended check per temporary table.', 1;

SET @ExpectedLegacyStrategyIdentityConstraintNormalized = LOWER(
    REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
        @ExpectedLegacyStrategyIdentityConstraintDefinition,
        N' ', N''), NCHAR(9), N''), NCHAR(10), N''), NCHAR(13), N''),
        N'[', N''), N']', N''));

SET @ExpectedFinalStrategyIdentityConstraintNormalized = LOWER(
    REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
        @ExpectedFinalStrategyIdentityConstraintDefinition,
        N' ', N''), NCHAR(9), N''), NCHAR(10), N''), NCHAR(13), N''),
        N'[', N''), N']', N''));

SET @ExpectedLeadershipConstraintNormalized = LOWER(
    REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
        @ExpectedLeadershipConstraintDefinition,
        N' ', N''), NCHAR(9), N''), NCHAR(10), N''), NCHAR(13), N''),
        N'[', N''), N']', N''));

-- Determine whether this is the exact first-run or exact idempotent-rerun schema
-- before selecting which strategy identity definition is permitted.
SELECT
    @ActiveColumnCount = COUNT(*),
    @NullableActiveColumnCount = SUM(CONVERT(INT, c.is_nullable))
FROM sys.columns AS c
JOIN sys.types AS t ON t.user_type_id = c.user_type_id
WHERE c.object_id = OBJECT_ID(N'dbo.LeadershipData')
  AND c.name IN (N'ActiveAdvancers', N'ActiveDecliners', N'ActiveN')
  AND t.name = N'int'
  AND c.max_length = 4;

IF @ActiveColumnCount <> 3
    THROW 51074, 'The three expected INT leadership observation columns are required.', 1;

IF @NullableActiveColumnCount = 0
    SET @IsFirstApplication = 1;
ELSE IF @NullableActiveColumnCount = 3
    SET @IsFirstApplication = 0;
ELSE
    THROW 51077, 'Partial leadership observation nullability is not a supported migration state.', 1;

-- First-run requires the exact legacy ADR-0042 check. Rerun requires the exact
-- strengthened check that this migration installs.
IF
(
    SELECT COUNT(*)
    FROM sys.columns AS c
    JOIN sys.types AS t ON t.user_type_id = c.user_type_id
    WHERE c.object_id = OBJECT_ID(N'dbo.StrategyVersion')
      AND
      (
          (c.name = N'InitialCodeCommit' AND t.name = N'nvarchar' AND c.max_length = 256 AND c.is_nullable = 1)
          OR
          (c.name = N'DecisionRef' AND t.name = N'nvarchar' AND c.max_length = 128 AND c.is_nullable = 1)
      )
) <> 2
    THROW 51071, 'The complete ADR-0042 strategy identity columns are required.', 1;

SELECT
    @StrategyIdentityConstraintCount = COUNT(*),
    @StrategyIdentityConstraintDefinition = MAX([definition])
FROM sys.check_constraints
WHERE [parent_object_id] = OBJECT_ID(N'dbo.StrategyVersion')
  AND [name] = N'CK_StrategyVersion_CodeIdentity'
  AND [is_disabled] = 0
  AND [is_not_trusted] = 0
  AND [is_not_for_replication] = 0;

SET @StrategyIdentityConstraintNormalized = LOWER(
    REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
        @StrategyIdentityConstraintDefinition,
        N' ', N''), NCHAR(9), N''), NCHAR(10), N''), NCHAR(13), N''),
        N'[', N''), N']', N''));

IF @StrategyIdentityConstraintCount <> 1
    OR @StrategyIdentityConstraintNormalized IS NULL
    OR @StrategyIdentityConstraintNormalized <>
        CASE WHEN @IsFirstApplication = 1
            THEN @ExpectedLegacyStrategyIdentityConstraintNormalized
            ELSE @ExpectedFinalStrategyIdentityConstraintNormalized
        END
    THROW 51072, 'The exact enabled and trusted strategy identity check for this migration state is required.', 1;

IF EXISTS
(
    SELECT 1
    FROM dbo.StrategyVersion
    WHERE ([InitialCodeCommit] IS NULL AND [DecisionRef] IS NOT NULL)
       OR ([InitialCodeCommit] IS NOT NULL AND [DecisionRef] IS NULL)
       OR ([InitialCodeCommit] IS NOT NULL AND LEN(LTRIM(RTRIM([InitialCodeCommit]))) NOT BETWEEN 7 AND 128)
       OR ([DecisionRef] IS NOT NULL AND LEN(LTRIM(RTRIM([DecisionRef]))) NOT BETWEEN 1 AND 64)
)
    THROW 51073, 'Invalid or partial strategy code identity exists.', 1;

SELECT
    @LeadershipConstraintCount = COUNT(*),
    @LeadershipConstraintDefinition = MAX([definition])
FROM sys.check_constraints
WHERE [parent_object_id] = OBJECT_ID(N'dbo.LeadershipData')
  AND [name] = N'CK_LeadershipData_ActiveBreadthObservation'
  AND [is_disabled] = 0
  AND [is_not_trusted] = 0
  AND [is_not_for_replication] = 0;

SET @LeadershipConstraintNormalized = LOWER(
    REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
        @LeadershipConstraintDefinition,
        N' ', N''), NCHAR(9), N''), NCHAR(10), N''), NCHAR(13), N''),
        N'[', N''), N']', N''));

IF @IsFirstApplication = 1
BEGIN
    IF OBJECT_ID(N'dbo.CK_LeadershipData_ActiveBreadthObservation', N'C') IS NOT NULL
        THROW 51075, 'The leadership observation check unexpectedly exists on the first-run schema.', 1;
END
ELSE
BEGIN
    IF @LeadershipConstraintCount <> 1
        OR @LeadershipConstraintNormalized IS NULL
        OR @LeadershipConstraintNormalized <> @ExpectedLeadershipConstraintNormalized
        THROW 51076, 'The nullable leadership schema lacks the exact enabled and trusted observation check.', 1;
END;

-- Refuse partial observations and every invalid non-sentinel observation before changing schema or data.
IF EXISTS
(
    SELECT 1
    FROM dbo.LeadershipData
    WHERE
        (CASE WHEN [ActiveAdvancers] IS NULL THEN 1 ELSE 0 END
         + CASE WHEN [ActiveDecliners] IS NULL THEN 1 ELSE 0 END
         + CASE WHEN [ActiveN] IS NULL THEN 1 ELSE 0 END) IN (1, 2)
       OR
        (
            [ActiveAdvancers] IS NOT NULL
            AND [ActiveDecliners] IS NOT NULL
            AND [ActiveN] IS NOT NULL
            AND NOT ([ActiveAdvancers] = 0 AND [ActiveDecliners] = 0 AND [ActiveN] = 0)
            AND
            (
                [ActiveAdvancers] < 0
                OR [ActiveDecliners] < 0
                OR [ActiveN] <= 0
                OR CONVERT(BIGINT, [ActiveAdvancers]) + [ActiveDecliners] > [ActiveN]
            )
        )
)
    THROW 51078, 'Partial or invalid non-sentinel leadership observations exist.', 1;

SELECT @SentinelRowsBefore = COUNT_BIG(*)
FROM dbo.LeadershipData
WHERE [ActiveAdvancers] = 0 AND [ActiveDecliners] = 0 AND [ActiveN] = 0;

IF @IsFirstApplication = 0 AND @SentinelRowsBefore <> 0
    THROW 51079, 'An idempotent rerun requires the exact final state with no remaining sentinel triples.', 1;

-- Refuse strategy identity collisions or a partially completed activation.
IF EXISTS
(
    SELECT 1
    FROM dbo.StrategyVersion WITH (UPDLOCK, HOLDLOCK)
    WHERE [VersionName] = @SuccessorName
      AND [VersionId] <> @SuccessorId
)
    THROW 51080, 'The v3.2 strategy name exists under another ID.', 1;

IF EXISTS
(
    SELECT 1
    FROM dbo.StrategyVersion WITH (UPDLOCK, HOLDLOCK)
    WHERE [VersionId] = @SuccessorId
      AND
      (
          [VersionName] <> @SuccessorName
          OR ISNULL([InitialCodeCommit], N'') <> @SuccessorCodeCommit
          OR ISNULL([DecisionRef], N'') <> @SuccessorDecisionRef
      )
)
    THROW 51081, 'The fixed v3.2 strategy ID exists with unexpected identity values.', 1;

IF NOT EXISTS
(
    SELECT 1
    FROM dbo.StrategyVersion WITH (UPDLOCK, HOLDLOCK)
    WHERE [VersionId] = @PredecessorId
      AND [VersionName] = @PredecessorName
      AND [InitialCodeCommit] = @PredecessorCodeCommit
      AND [DecisionRef] = @PredecessorDecisionRef
)
    THROW 51082, 'The exact ADR-0042 v3.1 predecessor does not exist.', 1;

IF @IsFirstApplication = 1
BEGIN
    IF EXISTS (SELECT 1 FROM dbo.StrategyVersion WHERE [VersionId] = @SuccessorId)
        THROW 51083, 'The v3.2 successor already exists on the first-run leadership schema.', 1;

    IF (SELECT COUNT(*) FROM dbo.StrategyVersion WITH (UPDLOCK, HOLDLOCK) WHERE [IsActive] = 1) <> 1
        OR NOT EXISTS
        (
            SELECT 1
            FROM dbo.StrategyVersion
            WHERE [VersionId] = @PredecessorId AND [IsActive] = 1
        )
        THROW 51084, 'The exact v3.1 predecessor must be the sole active strategy before first application.', 1;
END
ELSE
BEGIN
    IF (SELECT COUNT(*) FROM dbo.StrategyVersion WITH (UPDLOCK, HOLDLOCK) WHERE [IsActive] = 1) <> 1
        OR NOT EXISTS
        (
            SELECT 1
            FROM dbo.StrategyVersion
            WHERE [VersionId] = @SuccessorId
              AND [VersionName] = @SuccessorName
              AND [InitialCodeCommit] = @SuccessorCodeCommit
              AND [DecisionRef] = @SuccessorDecisionRef
              AND [IsActive] = 1
        )
        OR NOT EXISTS
        (
            SELECT 1
            FROM dbo.StrategyVersion
            WHERE [VersionId] = @PredecessorId AND [IsActive] = 0
        )
        THROW 51085, 'An idempotent rerun requires the exact final v3.2 activation state.', 1;
END;

-- Capture all affected and protected row counts plus exact historical references.
SELECT @LeadershipRowsBefore = COUNT_BIG(*) FROM dbo.LeadershipData;
SELECT @StrategyVersionRowsBefore = COUNT_BIG(*) FROM dbo.StrategyVersion;
SELECT @StrategyVersionModelRowsBefore = COUNT_BIG(*) FROM dbo.StrategyVersionModel;
SELECT @CalibrationRunRowsBefore = COUNT_BIG(*) FROM dbo.CalibrationRun;
SELECT @CalibrationCandidateRowsBefore = COUNT_BIG(*) FROM dbo.CalibrationCandidate;
SELECT @CalibrationLensRowsBefore = COUNT_BIG(*) FROM dbo.CalibrationLensEvaluation;
SELECT @CalibrationDefinitionRowsBefore = COUNT_BIG(*) FROM dbo.CalibrationOutcomeDefinition;
SELECT @CalibrationOutcomeRowsBefore = COUNT_BIG(*) FROM dbo.CalibrationCandidateOutcome;
SELECT @PredecessorModelCount = COUNT_BIG(*) FROM dbo.StrategyVersionModel WHERE [VersionId] = @PredecessorId;

INSERT INTO @CalibrationRunReferences ([RunId], [StrategyVersionId])
SELECT [RunId], [StrategyVersionId]
FROM dbo.CalibrationRun;

INSERT INTO @CalibrationCandidateReferences ([CandidateId], [RunId])
SELECT [CandidateId], [RunId]
FROM dbo.CalibrationCandidate;

INSERT INTO @CalibrationLensReferences ([LensEvaluationId], [CandidateId])
SELECT [LensEvaluationId], [CandidateId]
FROM dbo.CalibrationLensEvaluation;

INSERT INTO @CalibrationOutcomeReferences ([CandidateOutcomeId], [CandidateId], [OutcomeDefinitionId])
SELECT [CandidateOutcomeId], [CandidateId], [OutcomeDefinitionId]
FROM dbo.CalibrationCandidateOutcome;

IF @IsFirstApplication = 1
BEGIN
    ALTER TABLE dbo.StrategyVersion
        DROP CONSTRAINT [CK_StrategyVersion_CodeIdentity];

    ALTER TABLE dbo.StrategyVersion WITH CHECK
        ADD CONSTRAINT [CK_StrategyVersion_CodeIdentity] CHECK
        (
            ([InitialCodeCommit] IS NULL AND [DecisionRef] IS NULL)
            OR
            (
                [InitialCodeCommit] IS NOT NULL
                AND [DecisionRef] IS NOT NULL
                AND LEN(LTRIM(RTRIM([InitialCodeCommit]))) BETWEEN 7 AND 128
                AND LEN(LTRIM(RTRIM([DecisionRef]))) BETWEEN 1 AND 64
            )
        );

    ALTER TABLE dbo.StrategyVersion
        CHECK CONSTRAINT [CK_StrategyVersion_CodeIdentity];

    ALTER TABLE dbo.LeadershipData ALTER COLUMN [ActiveAdvancers] INT NULL;
    ALTER TABLE dbo.LeadershipData ALTER COLUMN [ActiveDecliners] INT NULL;
    ALTER TABLE dbo.LeadershipData ALTER COLUMN [ActiveN] INT NULL;

    UPDATE dbo.LeadershipData
    SET [ActiveAdvancers] = NULL,
        [ActiveDecliners] = NULL,
        [ActiveN] = NULL
    WHERE [ActiveAdvancers] = 0
      AND [ActiveDecliners] = 0
      AND [ActiveN] = 0;

    SET @NormalizedSentinelCount = @@ROWCOUNT;

    IF @NormalizedSentinelCount <> @SentinelRowsBefore
        THROW 51086, 'The normalized sentinel count did not match the guarded preflight count.', 1;

    ALTER TABLE dbo.LeadershipData WITH CHECK
        ADD CONSTRAINT [CK_LeadershipData_ActiveBreadthObservation] CHECK
        (
            (
                [ActiveAdvancers] IS NULL
                AND [ActiveDecliners] IS NULL
                AND [ActiveN] IS NULL
            )
            OR
            (
                [ActiveAdvancers] IS NOT NULL
                AND [ActiveDecliners] IS NOT NULL
                AND [ActiveN] IS NOT NULL
                AND [ActiveAdvancers] >= 0
                AND [ActiveDecliners] >= 0
                AND [ActiveN] > 0
                AND CONVERT(BIGINT, [ActiveAdvancers]) + [ActiveDecliners] <= [ActiveN]
            )
        );

    ALTER TABLE dbo.LeadershipData
        CHECK CONSTRAINT [CK_LeadershipData_ActiveBreadthObservation];

    INSERT INTO dbo.StrategyVersion
    (
        [VersionId],[VersionName],[Description],[IsActive],
        [MinCompositeScore],[MinDirectionProb],[RegressionVeto],[StopLossPercent],
        [WarningPercent],[MaxPositions],[CreatedUtc],[Notes],
        [InitialCodeCommit],[DecisionRef],
        [MinBreakoutProb],[MinDirectionEdge],[MaxDownProb],[BreadthVetoThreshold],
        [StrongBreakoutOverride],[StrongEdgeOverride]
    )
    SELECT
        @SuccessorId,
        @SuccessorName,
        N'Identity-only successor preserving leadership-source missingness under ADR-0043.',
        0,
        [MinCompositeScore],[MinDirectionProb],[RegressionVeto],[StopLossPercent],
        [WarningPercent],[MaxPositions],SYSUTCDATETIME(),
        N'Thresholds, model associations, gates, ranking formulas, and execution policy cloned unchanged from predecessor '
            + CONVERT(NVARCHAR(36), @PredecessorId) + N'.',
        @SuccessorCodeCommit,@SuccessorDecisionRef,
        [MinBreakoutProb],[MinDirectionEdge],[MaxDownProb],[BreadthVetoThreshold],
        [StrongBreakoutOverride],[StrongEdgeOverride]
    FROM dbo.StrategyVersion
    WHERE [VersionId] = @PredecessorId;

    INSERT INTO dbo.StrategyVersionModel
        ([VersionId],[ModelId],[CompositeWeight],[IsRequired],[Role])
    SELECT @SuccessorId,[ModelId],[CompositeWeight],[IsRequired],[Role]
    FROM dbo.StrategyVersionModel
    WHERE [VersionId] = @PredecessorId;

    UPDATE dbo.StrategyVersion
    SET [IsActive] = CASE WHEN [VersionId] = @SuccessorId THEN 1 ELSE 0 END
    WHERE [IsActive] = 1 OR [VersionId] = @SuccessorId;
END;

-- Verify the exact final schema and trusted constraint definition.
SET @StrategyIdentityConstraintDefinition = NULL;
SET @StrategyIdentityConstraintCount = 0;
SELECT
    @StrategyIdentityConstraintCount = COUNT(*),
    @StrategyIdentityConstraintDefinition = MAX([definition])
FROM sys.check_constraints
WHERE [parent_object_id] = OBJECT_ID(N'dbo.StrategyVersion')
  AND [name] = N'CK_StrategyVersion_CodeIdentity'
  AND [is_disabled] = 0
  AND [is_not_trusted] = 0
  AND [is_not_for_replication] = 0;

SET @StrategyIdentityConstraintNormalized = LOWER(
    REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
        @StrategyIdentityConstraintDefinition,
        N' ', N''), NCHAR(9), N''), NCHAR(10), N''), NCHAR(13), N''),
        N'[', N''), N']', N''));

IF @StrategyIdentityConstraintCount <> 1
    OR @StrategyIdentityConstraintNormalized IS NULL
    OR @StrategyIdentityConstraintNormalized <> @ExpectedFinalStrategyIdentityConstraintNormalized
    THROW 51098, 'The final strengthened identity check is missing, disabled, untrusted, replicated, or unexpected.', 1;

IF
(
    SELECT COUNT(*)
    FROM sys.columns AS c
    JOIN sys.types AS t ON t.user_type_id = c.user_type_id
    WHERE c.object_id = OBJECT_ID(N'dbo.LeadershipData')
      AND c.name IN (N'ActiveAdvancers', N'ActiveDecliners', N'ActiveN')
      AND t.name = N'int'
      AND c.max_length = 4
      AND c.is_nullable = 1
) <> 3
    THROW 51087, 'The final leadership observation columns are not all nullable INT.', 1;

SET @LeadershipConstraintDefinition = NULL;
SET @LeadershipConstraintCount = 0;
SELECT
    @LeadershipConstraintCount = COUNT(*),
    @LeadershipConstraintDefinition = MAX([definition])
FROM sys.check_constraints
WHERE [parent_object_id] = OBJECT_ID(N'dbo.LeadershipData')
  AND [name] = N'CK_LeadershipData_ActiveBreadthObservation'
  AND [is_disabled] = 0
  AND [is_not_trusted] = 0
  AND [is_not_for_replication] = 0;

SET @LeadershipConstraintNormalized = LOWER(
    REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
        @LeadershipConstraintDefinition,
        N' ', N''), NCHAR(9), N''), NCHAR(10), N''), NCHAR(13), N''),
        N'[', N''), N']', N''));

IF @LeadershipConstraintCount <> 1
    OR @LeadershipConstraintNormalized IS NULL
    OR @LeadershipConstraintNormalized <> @ExpectedLeadershipConstraintNormalized
    THROW 51088, 'The final leadership observation check is missing, disabled, untrusted, or unexpected.', 1;

IF EXISTS
(
    SELECT 1
    FROM dbo.LeadershipData
    WHERE NOT
    (
        ([ActiveAdvancers] IS NULL AND [ActiveDecliners] IS NULL AND [ActiveN] IS NULL)
        OR
        (
            [ActiveAdvancers] IS NOT NULL
            AND [ActiveDecliners] IS NOT NULL
            AND [ActiveN] IS NOT NULL
            AND [ActiveAdvancers] >= 0
            AND [ActiveDecliners] >= 0
            AND [ActiveN] > 0
            AND CONVERT(BIGINT, [ActiveAdvancers]) + [ActiveDecliners] <= [ActiveN]
        )
    )
)
    THROW 51089, 'An invalid leadership observation remains after normalization.', 1;

IF EXISTS
(
    SELECT 1
    FROM dbo.LeadershipData
    WHERE [ActiveAdvancers] = 0 AND [ActiveDecliners] = 0 AND [ActiveN] = 0
)
    THROW 51090, 'A legacy 0/0/0 leadership sentinel remains after normalization.', 1;

-- Verify sole activation and exact threshold/model equality in both directions.
IF (SELECT COUNT(*) FROM dbo.StrategyVersion WHERE [IsActive] = 1) <> 1
    OR NOT EXISTS
    (
        SELECT 1
        FROM dbo.StrategyVersion
        WHERE [VersionId] = @SuccessorId
          AND [VersionName] = @SuccessorName
          AND [InitialCodeCommit] = @SuccessorCodeCommit
          AND [DecisionRef] = @SuccessorDecisionRef
          AND [IsActive] = 1
    )
    OR NOT EXISTS
    (
        SELECT 1
        FROM dbo.StrategyVersion
        WHERE [VersionId] = @PredecessorId
          AND [VersionName] = @PredecessorName
          AND [IsActive] = 0
    )
    THROW 51091, 'The exact v3.2 successor is not solely active or v3.1 is not inactive.', 1;

IF EXISTS
(
    SELECT [MinCompositeScore],[MinDirectionProb],[RegressionVeto],[StopLossPercent],
           [WarningPercent],[MaxPositions],[MinBreakoutProb],[MinDirectionEdge],
           [MaxDownProb],[BreadthVetoThreshold],[StrongBreakoutOverride],[StrongEdgeOverride]
    FROM dbo.StrategyVersion WHERE [VersionId] = @SuccessorId
    EXCEPT
    SELECT [MinCompositeScore],[MinDirectionProb],[RegressionVeto],[StopLossPercent],
           [WarningPercent],[MaxPositions],[MinBreakoutProb],[MinDirectionEdge],
           [MaxDownProb],[BreadthVetoThreshold],[StrongBreakoutOverride],[StrongEdgeOverride]
    FROM dbo.StrategyVersion WHERE [VersionId] = @PredecessorId
)
OR EXISTS
(
    SELECT [MinCompositeScore],[MinDirectionProb],[RegressionVeto],[StopLossPercent],
           [WarningPercent],[MaxPositions],[MinBreakoutProb],[MinDirectionEdge],
           [MaxDownProb],[BreadthVetoThreshold],[StrongBreakoutOverride],[StrongEdgeOverride]
    FROM dbo.StrategyVersion WHERE [VersionId] = @PredecessorId
    EXCEPT
    SELECT [MinCompositeScore],[MinDirectionProb],[RegressionVeto],[StopLossPercent],
           [WarningPercent],[MaxPositions],[MinBreakoutProb],[MinDirectionEdge],
           [MaxDownProb],[BreadthVetoThreshold],[StrongBreakoutOverride],[StrongEdgeOverride]
    FROM dbo.StrategyVersion WHERE [VersionId] = @SuccessorId
)
    THROW 51092, 'The v3.2 thresholds differ from the v3.1 predecessor.', 1;

IF EXISTS
(
    SELECT [ModelId],[CompositeWeight],[IsRequired],[Role]
    FROM dbo.StrategyVersionModel WHERE [VersionId] = @SuccessorId
    EXCEPT
    SELECT [ModelId],[CompositeWeight],[IsRequired],[Role]
    FROM dbo.StrategyVersionModel WHERE [VersionId] = @PredecessorId
)
OR EXISTS
(
    SELECT [ModelId],[CompositeWeight],[IsRequired],[Role]
    FROM dbo.StrategyVersionModel WHERE [VersionId] = @PredecessorId
    EXCEPT
    SELECT [ModelId],[CompositeWeight],[IsRequired],[Role]
    FROM dbo.StrategyVersionModel WHERE [VersionId] = @SuccessorId
)
    THROW 51093, 'The v3.2 model associations differ from the v3.1 predecessor.', 1;

-- Verify every affected count and exact historical run/outcome reference.
IF (SELECT COUNT_BIG(*) FROM dbo.LeadershipData) <> @LeadershipRowsBefore
    OR (SELECT COUNT_BIG(*) FROM dbo.StrategyVersion) <>
        @StrategyVersionRowsBefore + CASE WHEN @IsFirstApplication = 1 THEN 1 ELSE 0 END
    OR (SELECT COUNT_BIG(*) FROM dbo.StrategyVersionModel) <>
        @StrategyVersionModelRowsBefore + CASE WHEN @IsFirstApplication = 1 THEN @PredecessorModelCount ELSE 0 END
    OR (SELECT COUNT_BIG(*) FROM dbo.CalibrationRun) <> @CalibrationRunRowsBefore
    OR (SELECT COUNT_BIG(*) FROM dbo.CalibrationCandidate) <> @CalibrationCandidateRowsBefore
    OR (SELECT COUNT_BIG(*) FROM dbo.CalibrationLensEvaluation) <> @CalibrationLensRowsBefore
    OR (SELECT COUNT_BIG(*) FROM dbo.CalibrationOutcomeDefinition) <> @CalibrationDefinitionRowsBefore
    OR (SELECT COUNT_BIG(*) FROM dbo.CalibrationCandidateOutcome) <> @CalibrationOutcomeRowsBefore
    THROW 51094, 'A protected leadership, strategy, or calibration row count changed unexpectedly.', 1;

IF EXISTS
(
    SELECT [RunId], [StrategyVersionId] FROM @CalibrationRunReferences
    EXCEPT
    SELECT [RunId], [StrategyVersionId] FROM dbo.CalibrationRun
)
OR EXISTS
(
    SELECT [RunId], [StrategyVersionId] FROM dbo.CalibrationRun
    EXCEPT
    SELECT [RunId], [StrategyVersionId] FROM @CalibrationRunReferences
)
    THROW 51095, 'Historical CalibrationRun strategy references changed unexpectedly.', 1;

IF EXISTS
(
    SELECT [CandidateId], [RunId] FROM @CalibrationCandidateReferences
    EXCEPT
    SELECT [CandidateId], [RunId] FROM dbo.CalibrationCandidate
)
OR EXISTS
(
    SELECT [CandidateId], [RunId] FROM dbo.CalibrationCandidate
    EXCEPT
    SELECT [CandidateId], [RunId] FROM @CalibrationCandidateReferences
)
    THROW 51099, 'Historical CalibrationCandidate run references changed unexpectedly.', 1;

IF EXISTS
(
    SELECT [LensEvaluationId], [CandidateId] FROM @CalibrationLensReferences
    EXCEPT
    SELECT [LensEvaluationId], [CandidateId] FROM dbo.CalibrationLensEvaluation
)
OR EXISTS
(
    SELECT [LensEvaluationId], [CandidateId] FROM dbo.CalibrationLensEvaluation
    EXCEPT
    SELECT [LensEvaluationId], [CandidateId] FROM @CalibrationLensReferences
)
    THROW 51100, 'Historical CalibrationLensEvaluation candidate references changed unexpectedly.', 1;

IF EXISTS
(
    SELECT [CandidateOutcomeId], [CandidateId], [OutcomeDefinitionId]
    FROM @CalibrationOutcomeReferences
    EXCEPT
    SELECT [CandidateOutcomeId], [CandidateId], [OutcomeDefinitionId]
    FROM dbo.CalibrationCandidateOutcome
)
OR EXISTS
(
    SELECT [CandidateOutcomeId], [CandidateId], [OutcomeDefinitionId]
    FROM dbo.CalibrationCandidateOutcome
    EXCEPT
    SELECT [CandidateOutcomeId], [CandidateId], [OutcomeDefinitionId]
    FROM @CalibrationOutcomeReferences
)
    THROW 51096, 'Historical calibration outcome references changed unexpectedly.', 1;

COMMIT TRANSACTION;

SELECT
    @IsFirstApplication AS [WasFirstApplication],
    @LeadershipRowsBefore AS [LeadershipRowsPreserved],
    @SentinelRowsBefore AS [SentinelRowsBefore],
    @NormalizedSentinelCount AS [NormalizedSentinelCount],
    (SELECT COUNT_BIG(*) FROM dbo.LeadershipData WHERE [ActiveAdvancers] IS NULL AND [ActiveDecliners] IS NULL AND [ActiveN] IS NULL) AS [MissingObservationRows],
    (SELECT COUNT_BIG(*) FROM dbo.LeadershipData WHERE [ActiveAdvancers] = 0 AND [ActiveDecliners] = 0 AND [ActiveN] = 0) AS [RemainingSentinelRows];

SELECT
    [VersionId],[VersionName],[Description],[IsActive],[InitialCodeCommit],[DecisionRef],
    [CreatedUtc],[Notes]
FROM dbo.StrategyVersion
WHERE [VersionId] IN (@PredecessorId, @SuccessorId)
ORDER BY [CreatedUtc], [VersionId];

SELECT [VersionId],[ModelId],[CompositeWeight],[IsRequired],[Role]
FROM dbo.StrategyVersionModel
WHERE [VersionId] IN (@PredecessorId, @SuccessorId)
ORDER BY [VersionId],[Role],[ModelId];

SELECT
    @CalibrationRunRowsBefore AS [CalibrationRunRowsPreserved],
    @CalibrationCandidateRowsBefore AS [CalibrationCandidateRowsPreserved],
    @CalibrationLensRowsBefore AS [CalibrationLensRowsPreserved],
    @CalibrationDefinitionRowsBefore AS [CalibrationOutcomeDefinitionRowsPreserved],
    @CalibrationOutcomeRowsBefore AS [CalibrationCandidateOutcomeRowsPreserved],
    (SELECT COUNT_BIG(*) FROM dbo.CalibrationRun WHERE [StrategyVersionId] = @SuccessorId) AS [SuccessorCalibrationRunRows];
