USE [TraderDB];
GO

SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;

/*
    Activate the identity-only ADR-0041 strategy successor defined by ADR-0042.

    Expected precondition:
      - dbo.StrategyVersion and dbo.StrategyVersionModel exist.
      - InitialCodeCommit and DecisionRef are either both absent or both present.
      - Before first application, exactly one different strategy version is active.

    Data effect:
      - Adds nullable strategy code/decision identity columns and their paired-value check.
      - Clones the active strategy's thresholds and model associations into the fixed
        v3.1-rs-date-aligned identity.
      - Deactivates the predecessor and activates the successor.
      - Does not update, relabel, invalidate, or delete any CalibrationRun or outcome.

    Recovery:
      - The schema addition is intentionally additive. If the later data transaction
        fails, the new nullable columns remain and a reviewed rerun may continue.
      - Activation and model-association cloning are one transaction. Use the required
        fresh verified backup or a separately authorized corrective migration after a
        committed result; do not edit this file after application.

    Review and execute manually only after a fresh verified backup and explicit
    authorization. Do not deploy a DACPAC.
*/

IF OBJECT_ID(N'dbo.StrategyVersion', N'U') IS NULL
    OR OBJECT_ID(N'dbo.StrategyVersionModel', N'U') IS NULL
    THROW 51060, 'Strategy version tables do not exist. Migration was not started.', 1;

DECLARE @CodeColumnExists BIT =
    CASE WHEN COL_LENGTH(N'dbo.StrategyVersion', N'InitialCodeCommit') IS NULL THEN 0 ELSE 1 END;
DECLARE @DecisionColumnExists BIT =
    CASE WHEN COL_LENGTH(N'dbo.StrategyVersion', N'DecisionRef') IS NULL THEN 0 ELSE 1 END;

IF @CodeColumnExists <> @DecisionColumnExists
    THROW 51061, 'Partial strategy identity schema exists. Migration refused without changing data.', 1;

IF @CodeColumnExists = 0
BEGIN
    BEGIN TRANSACTION;

    EXEC sys.sp_executesql N'
        ALTER TABLE [dbo].[StrategyVersion]
            ADD [InitialCodeCommit] NVARCHAR(128) NULL,
                [DecisionRef] NVARCHAR(64) NULL;

        ALTER TABLE [dbo].[StrategyVersion]
            ADD CONSTRAINT [CK_StrategyVersion_CodeIdentity] CHECK
            (
                ([InitialCodeCommit] IS NULL AND [DecisionRef] IS NULL)
                OR
                (
                    LEN(LTRIM(RTRIM([InitialCodeCommit]))) BETWEEN 7 AND 128
                    AND LEN(LTRIM(RTRIM([DecisionRef]))) BETWEEN 1 AND 64
                )
            );';

    IF COL_LENGTH(N'dbo.StrategyVersion', N'InitialCodeCommit') IS NULL
        OR COL_LENGTH(N'dbo.StrategyVersion', N'DecisionRef') IS NULL
        OR OBJECT_ID(N'dbo.CK_StrategyVersion_CodeIdentity', N'C') IS NULL
        THROW 51062, 'Strategy identity schema verification failed.', 1;

    COMMIT TRANSACTION;
END;
GO

SET XACT_ABORT ON;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

IF COL_LENGTH(N'dbo.StrategyVersion', N'InitialCodeCommit') IS NULL
    OR COL_LENGTH(N'dbo.StrategyVersion', N'DecisionRef') IS NULL
    OR OBJECT_ID(N'dbo.CK_StrategyVersion_CodeIdentity', N'C') IS NULL
    THROW 51069, 'Complete strategy identity schema is required before activation.', 1;

DECLARE @VersionId UNIQUEIDENTIFIER = '99D52317-8D16-4F2A-8B97-AE9698972F55';
DECLARE @VersionName NVARCHAR(32) = N'v3.1-rs-date-aligned';
DECLARE @InitialCodeCommit NVARCHAR(128) = N'c51c0849fd1311b3797cc664a19988e553bbe122';
DECLARE @DecisionRef NVARCHAR(64) = N'ADR-0041';
DECLARE @PredecessorId UNIQUEIDENTIFIER;
DECLARE @PredecessorModelCount INT;

BEGIN TRANSACTION;

IF EXISTS (SELECT 1 FROM [dbo].[StrategyVersion] WITH (UPDLOCK, HOLDLOCK) WHERE [VersionId] = @VersionId)
BEGIN
    IF NOT EXISTS
    (
        SELECT 1
        FROM [dbo].[StrategyVersion]
        WHERE [VersionId] = @VersionId
          AND [VersionName] = @VersionName
          AND [InitialCodeCommit] = @InitialCodeCommit
          AND [DecisionRef] = @DecisionRef
          AND [IsActive] = 1
    )
        THROW 51063, 'The ADR-0042 strategy identity exists in an unexpected or inactive state.', 1;
END
ELSE
BEGIN
    IF EXISTS
    (
        SELECT 1 FROM [dbo].[StrategyVersion] WITH (UPDLOCK, HOLDLOCK)
        WHERE [VersionName] = @VersionName AND [VersionId] <> @VersionId
    )
        THROW 51064, 'The ADR-0042 strategy name exists under another ID.', 1;

    IF (SELECT COUNT(*) FROM [dbo].[StrategyVersion] WITH (UPDLOCK, HOLDLOCK) WHERE [IsActive] = 1) <> 1
        THROW 51065, 'Exactly one predecessor strategy must be active before identity activation.', 1;

    SELECT @PredecessorId = [VersionId]
    FROM [dbo].[StrategyVersion]
    WHERE [IsActive] = 1;

    IF @PredecessorId = @VersionId
        THROW 51066, 'The successor cannot be its own predecessor.', 1;

    SELECT @PredecessorModelCount = COUNT(*)
    FROM [dbo].[StrategyVersionModel]
    WHERE [VersionId] = @PredecessorId;

    INSERT INTO [dbo].[StrategyVersion]
    (
        [VersionId],[VersionName],[Description],[IsActive],
        [MinCompositeScore],[MinDirectionProb],[RegressionVeto],[StopLossPercent],
        [WarningPercent],[MaxPositions],[CreatedUtc],[Notes],
        [InitialCodeCommit],[DecisionRef],
        [MinBreakoutProb],[MinDirectionEdge],[MaxDownProb],[BreadthVetoThreshold],
        [StrongBreakoutOverride],[StrongEdgeOverride]
    )
    SELECT
        @VersionId,
        @VersionName,
        N'Identity-only successor with ADR-0041 date-aligned relative-strength inputs.',
        0,
        [MinCompositeScore],[MinDirectionProb],[RegressionVeto],[StopLossPercent],
        [WarningPercent],[MaxPositions],SYSUTCDATETIME(),
        N'Thresholds, model associations, gates, ranking formulas, and execution policy cloned unchanged from predecessor '
            + CONVERT(NVARCHAR(36), @PredecessorId) + N'.',
        @InitialCodeCommit,@DecisionRef,
        [MinBreakoutProb],[MinDirectionEdge],[MaxDownProb],[BreadthVetoThreshold],
        [StrongBreakoutOverride],[StrongEdgeOverride]
    FROM [dbo].[StrategyVersion]
    WHERE [VersionId] = @PredecessorId;

    INSERT INTO [dbo].[StrategyVersionModel]
        ([VersionId],[ModelId],[CompositeWeight],[IsRequired],[Role])
    SELECT @VersionId,[ModelId],[CompositeWeight],[IsRequired],[Role]
    FROM [dbo].[StrategyVersionModel]
    WHERE [VersionId] = @PredecessorId;

    IF (SELECT COUNT(*) FROM [dbo].[StrategyVersionModel] WHERE [VersionId] = @VersionId)
        <> @PredecessorModelCount
        THROW 51067, 'The successor model associations do not match the predecessor.', 1;

    UPDATE [dbo].[StrategyVersion]
    SET [IsActive] = CASE WHEN [VersionId] = @VersionId THEN 1 ELSE 0 END
    WHERE [IsActive] = 1 OR [VersionId] = @VersionId;
END;

IF (SELECT COUNT(*) FROM [dbo].[StrategyVersion] WHERE [IsActive] = 1) <> 1
    OR NOT EXISTS
    (
        SELECT 1
        FROM [dbo].[StrategyVersion]
        WHERE [VersionId] = @VersionId
          AND [VersionName] = @VersionName
          AND [InitialCodeCommit] = @InitialCodeCommit
          AND [DecisionRef] = @DecisionRef
          AND [IsActive] = 1
    )
    THROW 51068, 'The ADR-0042 strategy activation postcondition failed.', 1;

COMMIT TRANSACTION;

SELECT
    [VersionId],[VersionName],[Description],[IsActive],[InitialCodeCommit],[DecisionRef],
    [CreatedUtc],[Notes]
FROM [dbo].[StrategyVersion]
WHERE [VersionId] = @VersionId;

SELECT [VersionId],[ModelId],[CompositeWeight],[IsRequired],[Role]
FROM [dbo].[StrategyVersionModel]
WHERE [VersionId] = @VersionId
ORDER BY [Role],[ModelId];
